services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  news-feed-bot:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8088:8088"
    environment:
      BOT_TOKEN: "${BOT_TOKEN}"
      CONFIG_PATH: /app/config/config.yaml
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DBNAME: postgres
      FILTER_KEYWORDS: "Инвестиции, деньги, прибыль, вложения, акции, трейдинг, арбитраж, выгодные вклады, выгодные сделки"
volumes:
  postgres_data: