version: '3.8'

services:
  db:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  news-feed-bot:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    environment:
      CONFIG_PATH: /api/config/config.yaml
    volumes:
      - ./config:/api/config
    command: ["./news-feed-bot", "-config", "$${CONFIG_PATH}"]

volumes:
  postgres_data: