env: "local"

http_server:
  address: "0.0.0.0:8088"
  timeout: 4s
  idle_timeout: 60s
  user: "sj_shoff"
  password: ${HTTP_PASSWORD}

postgres:
  host: db
  port: "5432" 
  username: postgres
  password: ${POSTGRES_PASSWORD}
  dbname: postgres
  sslmode: disable

bot:
  telegram_bot_token: "${BOT_TOKEN}"
  telegram_channel_id: "${TELEGRAM_CHANNEL_ID}"
  fetch_interval: ${FETCH_INTERVAL}
  notification_interval: ${NOTIFICATION_INTERVAL}
  filter_keywords: ${FILTER_KEYWORDS}
  openai_key: "${OPENAI_KEY}"
  openai_prompt: "${OPENAI_PROMPT}"
  openai_model: "${OPENAI_MODEL}"