env: "local" # local, dev, prod
http_server:
  address: "0.0.0.0:8069"
  timeout: 4s
  idle_timeout: 60s
  user: "sj_shoff"
  password: "${HTTP_PASSWORD}"
postgres:
  host: db
  port: "5435"
  username: postgres
  password: "${POSTGRES_PASSWORD}"
  dbname: news_feed_bot
  sslmode: disable
bot:
  telegram_bot_token: "${TELEGRAM_TOKEN}"
  telegram_channel_id: 123456789
  fetch_interval: "10m"
  notification_interval: "1m"
  filter_keywords:
    - "keyword1"
    - "keyword2"
  openai_key: "${OPENAI_KEY}"
  openai_prompt: "Summarize the following news article:"
  openai_model: "gpt-3.5-turbo"