env: "local"

postgres:
  host: db
  port: "5432"
  username: postgres
  dbname: postgres
  sslmode: disable

fetch_interval: 5m
notification_interval: 10m
filter_keywords:
  - Инвестиции
  - деньги
  - прибыль
  - вложения
  - акции
  - трейдинг
  - арбитраж
  - выгодные вклады
  - выгодные сделки
openai_prompt: "Сделай саммари на русском языке"
openai_model: "gpt-4o-mini"